### ISSUE TITLE
Server side rendering

### ISSUE THREAD

**Issue by byCedric** [byCedric/GitHub-Website#58]
### Description of the feature
Implement a super lightweight server-side rendering mechanism.

### Motivation
It would help a lot of open graph integrations to show the proper information without having to render the page. This could also be a solution for [the PWA manifest issue](https://github.com/byCedric/GitHub-Website/issues/33).

### Additional context
I would recommend using [Koa](https://koajs.com/) as a simple server. Let's not overthink it yet, and only make a first version working (without code splitting etc)

**Comment by johnanisere** [comment]
Hi Cedric, in what case do we need this for example?

**Comment by byCedric** [comment]
I think this feature can be combined with the new #97 issue, I'll close this for now and add it to the other one.
