### ISSUE TITLE
User description's clickable GitHub mentions

### ISSUE THREAD

**Issue by byCedric** [byCedric/GitHub-Website#59]
### Description of the feature
As briefly mentioned in #56: clickable github mentions.

### Motivation
> I think it would make it a lot easier for people visiting your portfolio Github Website to explorer all the companies and people you mention.

### Additional context
The [highlighter is already implemented](https://github.com/byCedric/GitHub-Website/blob/765c927d067be1ecbf8849089417130ffcd4566c/src/molecules/user/user.js#L14-L17), it only needs a proper decorator to handle the `@xxx` transformation to `<a href="github/xxx">@xxx</a>`.

**Comment by johnanisere** [comment]
when clicked, should it open in a new tab or open in the current tab?

**Comment by byCedric** [comment]
Hi John! I think it should open in a new window. It's because the user opened the developer's website. When this user clicks on the link, it should be able to return to the website without the actual back button. Since this is not possible, I guess we should open it in a new window. 😄 Does that sound reasonable?

**Comment by johnanisere** [comment]
> Hi John! I think it should open in a new window. It's because the user opened the developer's website. When this user clicks on the link, it should be able to return to the website without the actual back button. Since this is not possible, I guess we should open it in a new window. 😄 Does that sound reasonable?

do you mean window or tab?

**Comment by byCedric** [comment]
Closed via #65
